language: node_js
node_js:
- '0.10'
install:
- npm install -g grunt-cli bower
- npm install
- bower install
script:
- npm test
notifications:
  email:
  - rashid.khan@elasticsearch.com
  hipchat:
    rooms:
      secure: a2FERvICecrUAR62vP4vrUCTG3haRzf6kSzDDzGu6SICEXWLRrK0xeNQDpdwDAfzFmaIJ6txpkmInvEFeNPYNngTgEDyfhqdIa/lW0Ermdg+1hL0dK6QJiVmT1V6LDB2mgtaTTmfontxJqq7P2tmr0zz8ny4Eqq3lUnwPxYFNNo=
    format: html
    on_success: change
    template:
    - ! '%{repository_slug}/%{branch} by %{author}: %{commit_message} (<a href="%{build_url}">open</a>)'